name: app_frontend
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider: ^6.1.1

  # API
  dio: ^5.4.0

  # Local Storage
  shared_preferences: ^2.2.2

  # Device Info
  device_info_plus: ^10.1.0

  # File
  path_provider: ^2.1.2
  open_file: ^3.3.2

  # Image
  image_picker: ^1.0.7

  # UI
  flutter_rating_bar: ^4.0.1
  shimmer: ^3.0.0
  fl_chart: ^0.66.0
  file_picker: ^11.0.2

flutter:
  uses-material-design: true

  # assets:
  #   - assets/images/